object AuxForm1: TAuxForm1
  Left = 0
  Top = 0
  AlphaBlend = True
  AlphaBlendValue = 10
  BorderStyle = bsNone
  Caption = 'Form2'
  ClientHeight = 450
  ClientWidth = 1166
  Color = clWhite
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'Tahoma'
  Font.Style = []
  OldCreateOrder = False
  PixelsPerInch = 96
  TextHeight = 13
end
